apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: k8soperator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: LatencyCheck is the Schema for the latencychecks API
      displayName: Latency Check
      kind: LatencyCheck
      name: latencychecks.latency.redhat.com
      version: v1alpha1
  description: Checks latencies for your application endpoints and can be integrated
    with RHACM
  displayName: Latency Checks Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - latency
  - ddosify
  - latencycheck
  - latencies
  - rhacm
  - acm
  links:
  - name: K8soperator
    url: https://k8soperator.domain
  maturity: alpha
  provider:
    name: Red Hat Telco Operations
    url: https://github.com/RHsyseng/
  version: 0.0.0
