apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: latencycheck-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: LatencyCheck is the Schema for the latencychecks API
      displayName: Latency Check
      kind: LatencyCheck
      name: latencychecks.latency.redhat.com
      version: v1alpha1
  description: tt
  displayName: tt
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - tt
  links:
  - name: Latencycheck Operator
    url: https://latencycheck-operator.domain
  maturity: alpha
  provider:
    name: tt
    url: tt
  version: 0.0.0
