FROM registry.fedoraproject.org/fedora:37
MAINTAINER Mario Vazquez <mario@redhat.com>

RUN set -x && \
    dnf -y update && \
    dnf install -y python3 python3-flask python3-requests && \
    dnf clean all && \
    rm -rf /var/cache/yum /var/cache/dnf

RUN mkdir -p /opt/fake-api 
COPY templates /opt/fake-api/templates/
COPY api.py cert.key cert.pem /opt/fake-api/
RUN chown -R 1024:1024 /opt/fake-api
WORKDIR /opt/fake-api/
USER 1024
ENTRYPOINT ["/usr/bin/python3", "-u", "/opt/fake-api/api.py"]



