apiVersion: latency.redhat.com/v1alpha1
kind: LatencyCheck
metadata:
  name: lc-shortlived
spec:
  targetURL: "https://google.com"
  numberOfRuns: 1
  waitInterval: "5s"
  locations:
  - "NA.*"
  outputLocationsNumber: 3
  acmIntegration:
    placementRuleName: "test"
    placementRuleNamespace: "latencychecks"
    placementRuleClusterReplicas: 1
    clusterLocationLabel: "testlabel"
  scheduled: false
  provider:
    providerName: "ddosify"
    apiKey: "changeme"
